"""Excel generation for Adaptation Card using openpyxl."""
import io
from pathlib import Path

import openpyxl

TEMPLATE_PATH = Path(__file__).parent.parent / "static" / "adaptation_template.xlsx"
SHEET_NAME = "Чек-лист"

# ── Dropdown options ──────────────────────────────────────────────────────────
OPTS_YES_NO_OTHER   = ["да", "нет", "иное"]
OPTS_YES_NO         = ["да", "нет"]
OPTS_RECON_TYPE     = ["Реконструкция", "Уплотнение", "Изменение МП", "Сокращение площадей", "Реконструкция с сокращением площадей"]
OPTS_OWNERSHIP      = ["аренда", "собственность"]
OPTS_HO_TYPE        = ["Встройка", "Вынос", "Встройка+Вынос"]
OPTS_BUILDING_LOC   = ["отдельностоящее", "внутри ТЦ", "пристроенное к жилому дому"]
OPTS_CEILING        = ["Подвесной армстронг", "Грильято", "Подвесной потолок отсутствует", "Частично подвесной, частично отсутствует", "Иное"]
OPTS_BUILDING_TYPE  = ["МКД", "ТЦ", "жилой дом", "пристроенное к жилому дому"]
OPTS_REPLACE        = ["да", "нет", "иное", "полная замена", "частичная замена"]
OPTS_REPLACE_REPAIR = ["да", "нет", "иное", "полная замена", "частичная замена", "полный ремонт"]
OPTS_REPAIR_FULL    = ["да", "нет", "иное", "полная замена", "частичная замена", "полный ремонт", "локальный ремонт"]
OPTS_WASH_ROBOT     = ["Робот", "Поломоечная машина", "нет"]

# ── Form field definitions ────────────────────────────────────────────────────
# key → (cell, label, options or None for free text)
FIELDS: list[tuple[str, str, str, list | None]] = [
    # Section 1: Общая информация
    ("tk_number",        "B5",  "Номер ТК",                                    None),
    ("recon_type",       "B6",  "Суть проекта",                                OPTS_RECON_TYPE),
    ("current_rto",      "B7",  "Текущий РТО (дневной)",                       None),
    ("projected_rto",    "B8",  "Прогнозируемый РТО (дневной)",                None),
    ("zoning_dev",       "B9",  "Разработка зонирования",                      OPTS_YES_NO_OTHER),
    ("zoning_wishes",    "B10", "Пожелания по зонированию",                    OPTS_YES_NO_OTHER),
    ("mp_revision",      "B11", "Пересмотр МП",                                OPTS_YES_NO_OTHER),
    ("real_estate",      "B12", "Недвижимость",                                OPTS_OWNERSHIP),
    ("open_facade",      "B13", "Открытый фасад",                              OPTS_YES_NO_OTHER),
    ("second_entrance",  "B14", "Второй вход",                                 OPTS_YES_NO_OTHER),
    ("ho_type",          "B15", "Тип ХО",                                      OPTS_HO_TYPE),
    ("sign_change",      "B16", "Замена вывески",                              OPTS_YES_NO_OTHER),
    ("led_facade",       "B17", "Светодиодная лента на фасаде (неон)",         OPTS_YES_NO_OTHER),
    ("light_structures", "B18", "Световые конструкции",                        OPTS_REPLACE_REPAIR),
    ("stela",            "B19", "Стелла",                                      OPTS_REPLACE_REPAIR),
    ("building_location","B20", "Строение",                                    OPTS_BUILDING_LOC),
    ("ceiling_tz",       "B21", "Тип потолков ТЗ",                             OPTS_CEILING),
    ("ceiling_bek",      "B22", "Тип потолков БЭК",                            OPTS_CEILING),
    ("ceiling_height",   "B23", "Высота потолков",                             None),
    ("building_type",    "B24", "Тип здания",                                  OPTS_BUILDING_TYPE),
    ("ownership_type",   "B25", "Тип собственности",                           OPTS_OWNERSHIP),
    ("online_zone",      "B26", "Зона онлайн",                                 OPTS_YES_NO),
    ("wall_demolition",  "B27", "Демонтаж старого оформления стен/колонн",     OPTS_REPLACE_REPAIR),
    ("vitrage_prep",     "B28", "Подготовка витражей к новой оклейке",         OPTS_REPLACE_REPAIR),
    ("service_options",  "B29", "Сервисные опции в ТЗ",                        None),

    # Section 2: Производство / Кухня (B=ГО, C=Размер, D=Тип витрины, E=Комментарий)
    ("bakery",              "B31", "Пекарня СП",               OPTS_YES_NO_OTHER),
    ("bakery_size",         "C31", "Пекарня — размер",         None),
    ("bakery_type",         "D31", "Пекарня — тип витрины",    None),
    ("bakery_comment",      "E31", "Пекарня — комментарий",    None),
    ("tandyr",              "B32", "Тандыр",                   OPTS_YES_NO_OTHER),
    ("tandyr_size",         "C32", "Тандыр — размер",          None),
    ("tandyr_type",         "D32", "Тандыр — тип витрины",     None),
    ("tandyr_comment",      "E32", "Тандыр — комментарий",     None),
    ("grill",               "B33", "Гриль",                    OPTS_YES_NO_OTHER),
    ("grill_size",          "C33", "Гриль — размер",           None),
    ("grill_type",          "D33", "Гриль — тип витрины",      None),
    ("grill_comment",       "E33", "Гриль — комментарий",      None),
    ("fish_fresh",          "B34", "Рыба на льду",             OPTS_YES_NO_OTHER),
    ("fish_fresh_size",     "C34", "Рыба на льду — размер",    None),
    ("fish_fresh_type",     "D34", "Рыба на льду — тип",       None),
    ("fish_fresh_comment",  "E34", "Рыба на льду — комм.",     None),
    ("fish_smoked",         "B35", "Рыба копчёная",            OPTS_YES_NO_OTHER),
    ("fish_smoked_size",    "C35", "Рыба копчёная — размер",   None),
    ("fish_smoked_type",    "D35", "Рыба копчёная — тип",      None),
    ("fish_smoked_comment", "E35", "Рыба копч. — комм.",       None),
    ("meat_chilled",        "B36", "Мясо охлаждённое",         OPTS_YES_NO_OTHER),
    ("meat_chilled_size",   "C36", "Мясо охл. — размер",       None),
    ("meat_chilled_type",   "D36", "Мясо охл. — тип",          None),
    ("meat_chilled_comment","E36", "Мясо охл. — комм.",        None),
    ("meat_shop",           "B37", "Мясная лавка",             OPTS_YES_NO_OTHER),
    ("meat_shop_size",      "C37", "Мясная лавка — размер",    None),
    ("meat_shop_type",      "D37", "Мясная лавка — тип",       None),
    ("meat_shop_comment",   "E37", "Мясная лавка — комм.",     None),
    ("cheese",              "B38", "Сыр",                      OPTS_YES_NO_OTHER),
    ("cheese_size",         "C38", "Сыр — размер",             None),
    ("cheese_type",         "D38", "Сыр — тип витрины",        None),
    ("cheese_comment",      "E38", "Сыр — комментарий",        None),
    ("sausage",             "B39", "Колбаса",                  OPTS_YES_NO_OTHER),
    ("sausage_size",        "C39", "Колбаса — размер",         None),
    ("sausage_type",        "D39", "Колбаса — тип витрины",    None),
    ("sausage_comment",     "E39", "Колбаса — комментарий",    None),
    ("salads",              "B40", "Салаты / ГБ",              OPTS_YES_NO_OTHER),
    ("salads_size",         "C40", "Салаты — размер",          None),
    ("salads_type",         "D40", "Салаты — тип витрины",     None),
    ("salads_comment",      "E40", "Салаты — комментарий",     None),
    ("pizza",               "B41", "Пицца",                    OPTS_YES_NO_OTHER),
    ("pizza_size",          "C41", "Пицца — размер",           None),
    ("pizza_type",          "D41", "Пицца — тип витрины",      None),
    ("pizza_comment",       "E41", "Пицца — комментарий",      None),
    ("shawarma",            "B42", "Шаверма",                  OPTS_YES_NO_OTHER),
    ("shawarma_size",       "C42", "Шаверма — размер",         None),
    ("shawarma_type",       "D42", "Шаверма — тип витрины",    None),
    ("shawarma_comment",    "E42", "Шаверма — комментарий",    None),
    ("pancakes",            "B43", "Блины",                    OPTS_YES_NO_OTHER),
    ("pancakes_size",       "C43", "Блины — размер",           None),
    ("pancakes_type",       "D43", "Блины — тип витрины",      None),
    ("pancakes_comment",    "E43", "Блины — комментарий",      None),
    ("coffee",              "B44", "Кофе-машина",              OPTS_YES_NO_OTHER),
    ("coffee_size",         "C44", "Кофе — размер",            None),
    ("coffee_type",         "D44", "Кофе — тип витрины",       None),
    ("coffee_comment",      "E44", "Кофе — комментарий",       None),
    ("cafe_zone",           "B45", "Зона кафе",                OPTS_YES_NO_OTHER),
    ("cafe_zone_size",      "C45", "Зона кафе — размер",       None),
    ("cafe_zone_type",      "D45", "Зона кафе — тип витрины",  None),
    ("cafe_zone_comment",   "E45", "Зона кафе — комментарий",  None),

    # Section 3: Оборудование ТЗ (B=Решение, C=Кол-во, E=Тип, F=Комментарий)
    ("cash_tables",              "B52", "Кассовые столы",                 OPTS_REPLACE),
    ("cash_size",                "C52", "Кассовые столы — кол-во",        None),
    ("cash_type",                "E52", "Кассовые столы — тип",           None),
    ("cash_comment",             "F52", "Кассовые столы — комментарий",   None),
    ("kso",                      "B53", "КСО",                            OPTS_REPLACE),
    ("kso_size",                 "C53", "КСО — кол-во",                   None),
    ("kso_type",                 "E53", "КСО — тип",                      None),
    ("kso_comment",              "F53", "КСО — комментарий",              None),
    ("marmite",                  "B54", "Мармиты",                        OPTS_REPLACE),
    ("marmite_count",            "C54", "Мармиты — кол-во",               None),
    ("marmite_type",             "E54", "Мармиты — тип",                  None),
    ("marmite_comment",          "F54", "Мармиты — комментарий",          None),
    ("grill_eq",                 "B55", "Гриль (оборудование)",           OPTS_REPLACE),
    ("grill_eq_count",           "C55", "Гриль — кол-во",                 None),
    ("grill_eq_type",            "E55", "Гриль — тип",                    None),
    ("grill_eq_comment",         "F55", "Гриль — комментарий",            None),
    ("oven",                     "B56", "Печь",                           OPTS_REPLACE),
    ("oven_count",               "C56", "Печь — кол-во",                  None),
    ("oven_type",                "E56", "Печь — тип",                     None),
    ("oven_comment",             "F56", "Печь — комментарий",             None),
    ("convection_oven",          "B57", "Пароконвектомат",                OPTS_REPLACE),
    ("convection_oven_count",    "C57", "Пароконвектомат — кол-во",       None),
    ("convection_oven_type",     "E57", "Пароконвектомат — тип",          None),
    ("convection_oven_comment",  "F57", "Пароконвект. — комментарий",     None),
    ("cool_shelves",             "B58", "Холодильные горки",              OPTS_REPLACE),
    ("cool_shelves_count",       "C58", "Хол. горки — кол-во",            None),
    ("cool_shelves_type",        "E58", "Хол. горки — тип",               None),
    ("cool_shelves_comment",     "F58", "Хол. горки — комментарий",       None),
    ("cool_shelves_1500",        "B59", "Холодильные горки H 1500",       OPTS_REPLACE),
    ("cool_shelves_1500_count",  "C59", "Хол. горки 1500 — кол-во",       None),
    ("cool_shelves_1500_type",   "E59", "Хол. горки 1500 — тип",          None),
    ("cool_shelves_1500_comment","F59", "Хол. горки 1500 — комм.",         None),
    ("cool_doors",               "B60", "Двери в холодильных горках",     OPTS_REPLACE),
    ("cool_doors_count",         "C60", "Двери в горках — кол-во",        None),
    ("cool_doors_type",          "E60", "Двери в горках — тип",           None),
    ("cool_doors_comment",       "F60", "Двери в горках — комм.",         None),
    ("ho_ikra",                  "B61", "ХО Икра",                        OPTS_REPLACE),
    ("ho_ikra_count",            "C61", "ХО Икра — кол-во",               None),
    ("ho_ikra_type",             "E61", "ХО Икра — тип",                  None),
    ("ho_ikra_comment",          "F61", "ХО Икра — комментарий",          None),
    ("lari",                     "B62", "Лари",                           OPTS_REPLACE),
    ("lari_count",               "C62", "Лари — кол-во",                  None),
    ("lari_type",                "E62", "Лари — тип",                     None),
    ("lari_comment",             "F62", "Лари — комментарий",             None),
    ("vizory",                   "B63", "Визоры",                         OPTS_REPLACE),
    ("vizory_count",             "C63", "Визоры — кол-во",                None),
    ("vizory_type",              "E63", "Визоры — тип",                   None),
    ("vizory_comment",           "F63", "Визоры — комментарий",           None),
    ("showcases",                "B64", "Витрины",                        OPTS_REPLACE),
    ("showcases_count",          "C64", "Витрины — кол-во",               None),
    ("showcases_type",           "E64", "Витрины — тип",                  None),
    ("showcases_comment",        "F64", "Витрины — комментарий",          None),
    ("bonety",                   "B65", "Бонеты",                         OPTS_REPLACE),
    ("bonety_count",             "C65", "Бонеты — кол-во",                None),
    ("bonety_type",              "E65", "Бонеты — тип",                   None),
    ("bonety_comment",           "F65", "Бонеты — комментарий",           None),
    ("freezer_cabinets",         "B66", "Морозильные шкафы",              OPTS_REPLACE),
    ("freezer_cabinets_count",   "C66", "Морозил. шкафы — кол-во",        None),
    ("freezer_cabinets_type",    "E66", "Морозил. шкафы — тип",           None),
    ("freezer_cabinets_comment", "F66", "Морозил. шкафы — комм.",         None),
    ("eq_bumpers",               "B67", "Отбойники оборудования",         OPTS_REPLACE),
    ("eq_bumpers_count",         "C67", "Отбойники — кол-во",             None),
    ("eq_bumpers_type",          "E67", "Отбойники — тип",                None),
    ("eq_bumpers_comment",       "F67", "Отбойники — комментарий",        None),
    ("ldsp",                     "B68", "ЛДСП",                           OPTS_REPLACE),
    ("ldsp_count",               "C68", "ЛДСП — кол-во",                  None),
    ("ldsp_type",                "E68", "ЛДСП — тип",                     None),
    ("ldsp_comment",             "F68", "ЛДСП — комментарий",             None),
    ("shelving",                 "B69", "Стеллажное оборудование",        OPTS_REPLACE),
    ("shelving_count",           "C69", "Стеллажи — кол-во",              None),
    ("shelving_type",            "E69", "Стеллажи — тип",                 None),
    ("shelving_comment",         "F69", "Стеллажи — комментарий",         None),
    ("shelving_sof",             "B70", "Стеллажное оборудование СОФ",    OPTS_REPLACE),
    ("shelving_sof_count",       "C70", "Стеллажи СОФ — кол-во",         None),
    ("shelving_sof_type",        "E70", "Стеллажи СОФ — тип",             None),
    ("shelving_sof_comment",     "F70", "Стеллажи СОФ — комм.",           None),
    ("shelving_bakery",          "B71", "Стеллажное оборудование Пекарня",OPTS_REPLACE),
    ("shelving_bakery_count",    "C71", "Стеллажи Пекарня — кол-во",      None),
    ("shelving_bakery_type",     "E71", "Стеллажи Пекарня — тип",         None),
    ("shelving_bakery_comment",  "F71", "Стеллажи Пекарня — комм.",       None),
    ("shopping_carts",           "B72", "Тележки покупательские",         OPTS_REPLACE),
    ("shopping_carts_count",     "C72", "Тележки — кол-во",               None),
    ("shopping_carts_type",      "E72", "Тележки — тип",                  None),
    ("shopping_carts_comment",   "F72", "Тележки — комментарий",          None),
    ("price_holders",            "B73", "Замена ценникодержателей",        ["да"]),
    ("shelving_recount",         "B74", "Пересчёт стеллажного оборудования (БУ)", OPTS_YES_NO),

    # Section 4: Оборудование ИТ (B=Замена, C=Размер, D=Кол-во, E=Тип, F=Комментарий)
    ("ad_monitors",              "B77", "Рекламные мониторы над кассами",    OPTS_REPLACE),
    ("ad_monitors_size",         "C77", "Мониторы — размер",                 None),
    ("ad_monitors_count",        "D77", "Мониторы — кол-во",                 None),
    ("ad_monitors_type",         "E77", "Мониторы — тип",                    None),
    ("ad_monitors_comment",      "F77", "Мониторы — комментарий",            None),
    ("weight_equip",             "B78", "Весовое оборудование",              OPTS_REPLACE),
    ("weight_equip_size",        "C78", "Весовое — размер",                  None),
    ("weight_equip_count",       "D78", "Весовое — кол-во",                  None),
    ("weight_equip_type",        "E78", "Весовое — тип",                     None),
    ("weight_equip_comment",     "F78", "Весовое — комментарий",             None),
    ("price_checkers",           "B79", "Прайс-чекеры",                      OPTS_REPLACE),
    ("price_checkers_size",      "C79", "Прайс-чекеры — размер",             None),
    ("price_checkers_count",     "D79", "Прайс-чекеры — кол-во",             None),
    ("price_checkers_type",      "E79", "Прайс-чекеры — тип",                None),
    ("price_checkers_comment",   "F79", "Прайс-чекеры — комм.",              None),
    ("sks",                      "B80", "СКС",                               OPTS_REPLACE),
    ("sks_size",                 "C80", "СКС — размер",                      None),
    ("sks_count",                "D80", "СКС — кол-во",                      None),
    ("sks_type",                 "E80", "СКС — тип",                         None),
    ("sks_comment",              "F80", "СКС — комментарий",                 None),
    ("announcement",             "B81", "Система коммерческого оповещения",  OPTS_REPLACE),
    ("announcement_size",        "C81", "СКО — размер",                      None),
    ("announcement_count",       "D81", "СКО — кол-во",                      None),
    ("announcement_type",        "E81", "СКО — тип",                         None),
    ("announcement_comment",     "F81", "СКО — комментарий",                 None),
    ("server_room",              "B82", "Серверная",                         OPTS_REPLACE),
    ("server_room_size",         "C82", "Серверная — размер",                None),
    ("server_room_count",        "D82", "Серверная — кол-во",                None),
    ("server_room_type",         "E82", "Серверная — тип",                   None),
    ("server_room_comment",      "F82", "Серверная — комментарий",           None),
    ("kkt",                      "B83", "Замена ККТ",                        OPTS_REPLACE),
    ("kkt_size",                 "C83", "ККТ — размер",                      None),
    ("kkt_count",                "D83", "ККТ — кол-во",                      None),
    ("kkt_type",                 "E83", "ККТ — тип",                         None),
    ("kkt_comment",              "F83", "ККТ — комментарий",                 None),
    ("sticker_printer",          "B84", "Принтер печати стикеров",           OPTS_REPLACE),
    ("sticker_printer_size",     "C84", "Принтер — размер",                  None),
    ("sticker_printer_count",    "D84", "Принтер — кол-во",                  None),
    ("sticker_printer_type",     "E84", "Принтер — тип",                     None),
    ("sticker_printer_comment",  "F84", "Принтер — комментарий",             None),
    ("cellular",                 "B85", "Усиление сотовой связи",            OPTS_REPLACE),
    ("cellular_size",            "C85", "Сотовая — размер",                  None),
    ("cellular_count",           "D85", "Сотовая — кол-во",                  None),
    ("cellular_type",            "E85", "Сотовая — тип",                     None),
    ("cellular_comment",         "F85", "Сотовая — комментарий",             None),
    ("wifi",                     "B86", "Вай-фай",                           OPTS_REPLACE),
    ("wifi_size",                "C86", "Вай-фай — размер",                  None),
    ("wifi_count",               "D86", "Вай-фай — кол-во",                  None),
    ("wifi_type",                "E86", "Вай-фай — тип",                     None),
    ("wifi_comment",             "F86", "Вай-фай — комментарий",             None),
    ("computers",                "B87", "Компьютеры",                        OPTS_REPLACE),
    ("computers_size",           "C87", "Компьютеры — размер",               None),
    ("computers_count",          "D87", "Компьютеры — кол-во",               None),
    ("computers_type",           "E87", "Компьютеры — тип",                  None),
    ("computers_comment",        "F87", "Компьютеры — комментарий",          None),

    # Section 5: Оборудование Бэкофиса (B=Замена, C=Размер, D=Кол-во, E=Тип, F=Комментарий)
    ("office_furniture",             "B90",  "Мебель офиса",                              OPTS_REPLACE),
    ("office_furniture_size",        "C90",  "Мебель офиса — размер",                     None),
    ("office_furniture_count",       "D90",  "Мебель офиса — кол-во",                     None),
    ("office_furniture_type",        "E90",  "Мебель офиса — тип",                        None),
    ("office_furniture_comment",     "F90",  "Мебель офиса — комм.",                      None),
    ("metal_furniture",              "B91",  "Мебель металлическая",                      OPTS_REPLACE),
    ("metal_furniture_size",         "C91",  "Мет. мебель — размер",                      None),
    ("metal_furniture_count",        "D91",  "Мет. мебель — кол-во",                      None),
    ("metal_furniture_type",         "E91",  "Мет. мебель — тип",                         None),
    ("metal_furniture_comment",      "F91",  "Мет. мебель — комм.",                       None),
    ("tech_equipment",               "B92",  "Технологическое оборудование",              OPTS_REPLACE),
    ("tech_equipment_size",          "C92",  "Тех. обор. — размер",                       None),
    ("tech_equipment_count",         "D92",  "Тех. обор. — кол-во",                       None),
    ("tech_equipment_type",          "E92",  "Тех. обор. — тип",                          None),
    ("tech_equipment_comment",       "F92",  "Тех. обор. — комм.",                        None),
    ("bek_shelving",                 "B93",  "Стеллажное оборудование БЭК",               OPTS_REPLACE),
    ("bek_shelving_size",            "C93",  "Стеллажи БЭК — размер",                     None),
    ("bek_shelving_count",           "D93",  "Стеллажи БЭК — кол-во",                     None),
    ("bek_shelving_type",            "E93",  "Стеллажи БЭК — тип",                        None),
    ("bek_shelving_comment",         "F93",  "Стеллажи БЭК — комм.",                      None),
    ("cargo_shelving",               "B94",  "Грузовые стеллажи в БЭК",                   OPTS_REPLACE),
    ("cargo_shelving_size",          "C94",  "Груз. стел. — размер",                      None),
    ("cargo_shelving_count",         "D94",  "Груз. стел. — кол-во",                      None),
    ("cargo_shelving_type",          "E94",  "Груз. стел. — тип",                         None),
    ("cargo_shelving_comment",       "F94",  "Груз. стел. — комм.",                       None),
    ("defect_fridge",                "B95",  "Холодильник для брака",                     OPTS_REPLACE),
    ("defect_fridge_size",           "C95",  "Хол. брака — размер",                       None),
    ("defect_fridge_count",          "D95",  "Хол. брака — кол-во",                       None),
    ("defect_fridge_type",           "E95",  "Хол. брака — тип",                          None),
    ("defect_fridge_comment",        "F95",  "Хол. брака — комм.",                        None),
    ("cryo_coolers",                 "B96",  "Холодильные камеры (воздухоохладители)",    OPTS_REPLACE),
    ("cryo_coolers_size",            "C96",  "ХК воздух. — размер",                       None),
    ("cryo_coolers_count",           "D96",  "ХК воздух. — кол-во",                       None),
    ("cryo_coolers_type",            "E96",  "ХК воздух. — тип",                          None),
    ("cryo_coolers_comment",         "F96",  "ХК воздух. — комм.",                        None),
    ("cryo_panels",                  "B97",  "Холодильные камеры (панели)",               OPTS_REPLACE),
    ("cryo_panels_size",             "C97",  "ХК панели — размер",                        None),
    ("cryo_panels_count",            "D97",  "ХК панели — кол-во",                        None),
    ("cryo_panels_type",             "E97",  "ХК панели — тип",                           None),
    ("cryo_panels_comment",          "F97",  "ХК панели — комм.",                         None),
    ("cryo_doors",                   "B98",  "Двери и фурнитура холодильных камер",       OPTS_REPLACE),
    ("cryo_doors_size",              "C98",  "Двери ХК — размер",                         None),
    ("cryo_doors_count",             "D98",  "Двери ХК — кол-во",                         None),
    ("cryo_doors_type",              "E98",  "Двери ХК — тип",                            None),
    ("cryo_doors_comment",           "F98",  "Двери ХК — комм.",                          None),
    ("cryo_shelving",                "B99",  "Стеллажи в холодильных камерах",            OPTS_REPLACE),
    ("cryo_shelving_size",           "C99",  "Стел. ХК — размер",                         None),
    ("cryo_shelving_count",          "D99",  "Стел. ХК — кол-во",                         None),
    ("cryo_shelving_type",           "E99",  "Стел. ХК — тип",                            None),
    ("cryo_shelving_comment",        "F99",  "Стел. ХК — комм.",                          None),
    ("chm_replace",                  "B100", "ЦХМ замена",                                OPTS_REPLACE),
    ("chm_replace_size",             "C100", "ЦХМ замена — размер",                       None),
    ("chm_replace_count",            "D100", "ЦХМ замена — кол-во",                       None),
    ("chm_replace_type",             "E100", "ЦХМ замена — тип",                          None),
    ("chm_replace_comment",          "F100", "ЦХМ замена — комм.",                        None),
    ("chm_relocate",                 "B101", "ЦХМ изменение месторасположения",           OPTS_REPLACE),
    ("chm_relocate_size",            "C101", "ЦХМ перемещ. — размер",                     None),
    ("chm_relocate_count",           "D101", "ЦХМ перемещ. — кол-во",                     None),
    ("chm_relocate_type",            "E101", "ЦХМ перемещ. — тип",                        None),
    ("chm_relocate_comment",         "F101", "ЦХМ перемещ. — комм.",                      None),
    ("condenser",                    "B102", "Конденсаторные блоки",                      OPTS_REPLACE),
    ("condenser_size",               "C102", "Конденс. — размер",                          None),
    ("condenser_count",              "D102", "Конденс. — кол-во",                          None),
    ("condenser_type",               "E102", "Конденс. — тип",                             None),
    ("condenser_comment",            "F102", "Конденс. — комм.",                           None),
    ("cargo_scales_15",              "B103", "Грузовые весы 1,5 т.",                      OPTS_REPLACE),
    ("cargo_scales_15_size",         "C103", "Весы 1.5т — размер",                        None),
    ("cargo_scales_15_count",        "D103", "Весы 1.5т — кол-во",                        None),
    ("cargo_scales_15_type",         "E103", "Весы 1.5т — тип",                           None),
    ("cargo_scales_15_comment",      "F103", "Весы 1.5т — комм.",                         None),
    ("cargo_scales_30",              "B104", "Грузовые весы до 30 кг",                    OPTS_REPLACE),
    ("cargo_scales_30_size",         "C104", "Весы 30кг — размер",                        None),
    ("cargo_scales_30_count",        "D104", "Весы 30кг — кол-во",                        None),
    ("cargo_scales_30_type",         "E104", "Весы 30кг — тип",                           None),
    ("cargo_scales_30_comment",      "F104", "Весы 30кг — комм.",                         None),
    ("press",                        "B105", "Пресс",                                     OPTS_REPLACE),
    ("press_size",                   "C105", "Пресс — размер",                             None),
    ("press_count",                  "D105", "Пресс — кол-во",                             None),
    ("press_type",                   "E105", "Пресс — тип",                                None),
    ("press_comment",                "F105", "Пресс — комментарий",                        None),
    ("hydraulic_carts",              "B106", "Гидравлические тележки",                    OPTS_REPLACE),
    ("hydraulic_carts_size",         "C106", "Гидр. тел. — размер",                       None),
    ("hydraulic_carts_count",        "D106", "Гидр. тел. — кол-во",                       None),
    ("hydraulic_carts_type",         "E106", "Гидр. тел. — тип",                          None),
    ("hydraulic_carts_comment",      "F106", "Гидр. тел. — комм.",                        None),

    # Section 6: Помещения Бэкофиса (B=Ремонт, C=Размер, D=Примечания)
    ("room_receiving",            "B110", "Приёмка",                                   OPTS_REPAIR_FULL),
    ("room_receiving_size",       "C110", "Приёмка — размер",                          None),
    ("room_receiving_comment",    "D110", "Приёмка — примечания",                      None),
    ("room_dining",               "B111", "Комната приёма пищи",                       OPTS_REPAIR_FULL),
    ("room_dining_size",          "C111", "Комн. питания — размер",                    None),
    ("room_dining_comment",       "D111", "Комн. питания — примечания",                None),
    ("room_office",               "B112", "Офис",                                      OPTS_REPAIR_FULL),
    ("room_office_size",          "C112", "Офис — размер",                             None),
    ("room_office_comment",       "D112", "Офис — примечания",                         None),
    ("room_changing",             "B113", "Раздевалки",                                OPTS_REPAIR_FULL),
    ("room_changing_size",        "C113", "Раздевалки — размер",                       None),
    ("room_changing_comment",     "D113", "Раздевалки — примечания",                   None),
    ("room_wc",                   "B114", "Сан. Узлы",                                 OPTS_REPAIR_FULL),
    ("room_wc_size",              "C114", "Сан. узлы — размер",                        None),
    ("room_wc_comment",           "D114", "Сан. узлы — примечания",                    None),
    ("room_floor",                "B115", "Напольное покрытие (бэк)",                  OPTS_REPAIR_FULL),
    ("room_floor_size",           "C115", "Полы бэк — размер",                         None),
    ("room_floor_comment",        "D115", "Полы бэк — примечания",                     None),
    ("room_cashroom",             "B116", "Главная касса",                             OPTS_REPAIR_FULL),
    ("room_cashroom_size",        "C116", "Гл. касса — размер",                        None),
    ("room_cashroom_comment",     "D116", "Гл. касса — примечания",                    None),
    ("room_bank_equip",           "B117", "Замена банковского оборудования",           OPTS_REPAIR_FULL),
    ("room_bank_equip_size",      "C117", "Банк. обор. — размер",                      None),
    ("room_bank_equip_comment",   "D117", "Банк. обор. — примечания",                  None),

    # Section 7: Помещение ТЗ (B=Ремонт, C=Размер, D=Кол-во, E=Тип, F=Комментарий)
    ("tz_floor",                  "B120", "Напольное покрытие (ТЗ)",                   OPTS_REPAIR_FULL),
    ("tz_floor_size",             "C120", "Полы ТЗ — размер",                          None),
    ("tz_floor_count",            "D120", "Полы ТЗ — кол-во",                          None),
    ("tz_floor_type",             "E120", "Полы ТЗ — тип",                             None),
    ("tz_floor_comment",          "F120", "Полы ТЗ — комментарий",                     None),
    ("tz_lighting",               "B121", "Освещение",                                 OPTS_REPAIR_FULL),
    ("tz_lighting_size",          "C121", "Освещение — размер",                        None),
    ("tz_lighting_count",         "D121", "Освещение — кол-во",                        None),
    ("tz_lighting_type",          "E121", "Освещение — тип",                           None),
    ("tz_lighting_comment",       "F121", "Освещение — комментарий",                   None),
    ("tz_accent_light",           "B122", "Акцентное освещение",                       OPTS_REPAIR_FULL),
    ("tz_accent_light_size",      "C122", "Акц. свет — размер",                        None),
    ("tz_accent_light_count",     "D122", "Акц. свет — кол-во",                        None),
    ("tz_accent_light_type",      "E122", "Акц. свет — тип",                           None),
    ("tz_accent_light_comment",   "F122", "Акц. свет — комментарий",                   None),
    ("tz_walls",                  "B123", "Look & Feel (покраска стен)",               OPTS_REPAIR_FULL),
    ("tz_walls_size",             "C123", "Стены — размер",                            None),
    ("tz_walls_count",            "D123", "Стены — кол-во",                            None),
    ("tz_walls_type",             "E123", "Стены — тип",                               None),
    ("tz_walls_comment",          "F123", "Стены — комментарий",                       None),
    ("tz_entrance_grp",           "B124", "Входная группа",                            OPTS_REPAIR_FULL),
    ("tz_entrance_grp_size",      "C124", "Вход. группа — размер",                     None),
    ("tz_entrance_grp_count",     "D124", "Вход. группа — кол-во",                     None),
    ("tz_entrance_grp_type",      "E124", "Вход. группа — тип",                        None),
    ("tz_entrance_grp_comment",   "F124", "Вход. группа — комментарий",                None),
    ("tz_auto_doors",             "B125", "Входные автоматические двери",              OPTS_REPAIR_FULL),
    ("tz_auto_doors_size",        "C125", "Авт. двери — размер",                       None),
    ("tz_auto_doors_count",       "D125", "Авт. двери — кол-во",                       None),
    ("tz_auto_doors_type",        "E125", "Авт. двери — тип",                          None),
    ("tz_auto_doors_comment",     "F125", "Авт. двери — комментарий",                  None),
    ("tz_mech_doors",             "B126", "Входные механические двери",                OPTS_REPAIR_FULL),
    ("tz_mech_doors_size",        "C126", "Мех. двери — размер",                       None),
    ("tz_mech_doors_count",       "D126", "Мех. двери — кол-во",                       None),
    ("tz_mech_doors_type",        "E126", "Мех. двери — тип",                          None),
    ("tz_mech_doors_comment",     "F126", "Мех. двери — комментарий",                  None),
    ("tz_porch",                  "B127", "Крыльцо",                                   OPTS_REPAIR_FULL),
    ("tz_porch_size",             "C127", "Крыльцо — размер",                          None),
    ("tz_porch_count",            "D127", "Крыльцо — кол-во",                          None),
    ("tz_porch_type",             "E127", "Крыльцо — тип",                             None),
    ("tz_porch_comment",          "F127", "Крыльцо — комментарий",                     None),
    ("tz_parking",                "B128", "Парковка",                                  OPTS_REPAIR_FULL),
    ("tz_parking_size",           "C128", "Парковка — размер",                         None),
    ("tz_parking_count",          "D128", "Парковка — кол-во",                         None),
    ("tz_parking_type",           "E128", "Парковка — тип",                            None),
    ("tz_parking_comment",        "F128", "Парковка — комментарий",                    None),
    ("tz_vitrages",               "B129", "Витражи (открытый фасад)",                  OPTS_REPAIR_FULL),
    ("tz_vitrages_size",          "C129", "Витражи — размер",                          None),
    ("tz_vitrages_count",         "D129", "Витражи — кол-во",                          None),
    ("tz_vitrages_type",          "E129", "Витражи — тип",                             None),
    ("tz_vitrages_comment",       "F129", "Витражи — комментарий",                     None),
    ("tz_imposty",                "B130", "Импосты открытого фасада",                  OPTS_REPAIR_FULL),
    ("tz_imposty_size",           "C130", "Импосты — размер",                          None),
    ("tz_imposty_count",          "D130", "Импосты — кол-во",                          None),
    ("tz_imposty_type",           "E130", "Импосты — тип",                             None),
    ("tz_imposty_comment",        "F130", "Импосты — комментарий",                     None),
    ("tz_ceiling",                "B131", "Потолок",                                   OPTS_REPAIR_FULL),
    ("tz_ceiling_size",           "C131", "Потолок — размер",                          None),
    ("tz_ceiling_count",          "D131", "Потолок — кол-во",                          None),
    ("tz_ceiling_type",           "E131", "Потолок — тип",                             None),
    ("tz_ceiling_comment",        "F131", "Потолок — комментарий",                     None),
    ("tz_announcement",           "B132", "Система оповещения",                        OPTS_REPAIR_FULL),
    ("tz_announcement_size",      "C132", "Сист. опов. — размер",                      None),
    ("tz_announcement_count",     "D132", "Сист. опов. — кол-во",                      None),
    ("tz_announcement_type",      "E132", "Сист. опов. — тип",                         None),
    ("tz_announcement_comment",   "F132", "Сист. опов. — комментарий",                 None),
    ("tz_fire_alarm",             "B133", "Пожарная сигнализация",                     OPTS_REPAIR_FULL),
    ("tz_fire_alarm_size",        "C133", "Пож. сигн. — размер",                       None),
    ("tz_fire_alarm_count",       "D133", "Пож. сигн. — кол-во",                       None),
    ("tz_fire_alarm_type",        "E133", "Пож. сигн. — тип",                          None),
    ("tz_fire_alarm_comment",     "F133", "Пож. сигн. — комментарий",                  None),
    ("tz_smoke",                  "B134", "Система дымоудаления",                      OPTS_REPAIR_FULL),
    ("tz_smoke_size",             "C134", "Дымоудал. — размер",                        None),
    ("tz_smoke_count",            "D134", "Дымоудал. — кол-во",                        None),
    ("tz_smoke_type",             "E134", "Дымоудал. — тип",                           None),
    ("tz_smoke_comment",          "F134", "Дымоудал. — комментарий",                   None),
    ("tz_aupt",                   "B135", "АУПТ",                                      OPTS_REPAIR_FULL),
    ("tz_aupt_size",              "C135", "АУПТ — размер",                             None),
    ("tz_aupt_count",             "D135", "АУПТ — кол-во",                             None),
    ("tz_aupt_type",              "E135", "АУПТ — тип",                                None),
    ("tz_aupt_comment",           "F135", "АУПТ — комментарий",                        None),
    ("tz_radiators",              "B136", "Радиаторное отопление",                     OPTS_REPAIR_FULL),
    ("tz_radiators_size",         "C136", "Радиаторы — размер",                        None),
    ("tz_radiators_count",        "D136", "Радиаторы — кол-во",                        None),
    ("tz_radiators_type",         "E136", "Радиаторы — тип",                           None),
    ("tz_radiators_comment",      "F136", "Радиаторы — комментарий",                   None),
    ("tz_heating",                "B137", "Система отопления",                         OPTS_REPAIR_FULL),
    ("tz_heating_size",           "C137", "Отопление — размер",                        None),
    ("tz_heating_count",          "D137", "Отопление — кол-во",                        None),
    ("tz_heating_type",           "E137", "Отопление — тип",                           None),
    ("tz_heating_comment",        "F137", "Отопление — комментарий",                   None),
    ("tz_conditioners",           "B138", "Кондиционеры",                              OPTS_REPAIR_FULL),
    ("tz_conditioners_size",      "C138", "Кондиц. — размер",                          None),
    ("tz_conditioners_count",     "D138", "Кондиц. — кол-во",                          None),
    ("tz_conditioners_type",      "E138", "Кондиц. — тип",                             None),
    ("tz_conditioners_comment",   "F138", "Кондиц. — комментарий",                     None),
    ("tz_partitions",             "B139", "Новые перегородки",                         OPTS_REPAIR_FULL),
    ("tz_partitions_size",        "C139", "Перегородки — размер",                      None),
    ("tz_partitions_count",       "D139", "Перегородки — кол-во",                      None),
    ("tz_partitions_type",        "E139", "Перегородки — тип",                         None),
    ("tz_partitions_comment",     "F139", "Перегородки — комментарий",                 None),
    ("tz_air_curtains",           "B140", "Тепловые завесы",                           OPTS_REPAIR_FULL),
    ("tz_air_curtains_size",      "C140", "Тепл. завесы — размер",                     None),
    ("tz_air_curtains_count",     "D140", "Тепл. завесы — кол-во",                     None),
    ("tz_air_curtains_type",      "E140", "Тепл. завесы — тип",                        None),
    ("tz_air_curtains_comment",   "F140", "Тепл. завесы — комментарий",                None),
    ("tz_lift_tables",            "B141", "Подъёмные столы",                           OPTS_REPAIR_FULL),
    ("tz_lift_tables_size",       "C141", "Подъём. столы — размер",                    None),
    ("tz_lift_tables_count",      "D141", "Подъём. столы — кол-во",                    None),
    ("tz_lift_tables_type",       "E141", "Подъём. столы — тип",                       None),
    ("tz_lift_tables_comment",    "F141", "Подъём. столы — комментарий",               None),
    ("tz_lifts",                  "B142", "Лифты/подъёмники",                          OPTS_REPAIR_FULL),
    ("tz_lifts_size",             "C142", "Лифты — размер",                            None),
    ("tz_lifts_count",            "D142", "Лифты — кол-во",                            None),
    ("tz_lifts_type",             "E142", "Лифты — тип",                               None),
    ("tz_lifts_comment",          "F142", "Лифты — комментарий",                       None),
    ("tz_sectional_gates",        "B143", "Секционные ворота",                         OPTS_REPAIR_FULL),
    ("tz_sectional_gates_size",   "C143", "Секц. ворота — размер",                     None),
    ("tz_sectional_gates_count",  "D143", "Секц. ворота — кол-во",                     None),
    ("tz_sectional_gates_type",   "E143", "Секц. ворота — тип",                        None),
    ("tz_sectional_gates_comment","F143", "Секц. ворота — комментарий",                None),
    ("tz_roller_gates",           "B144", "Рулонные ворота",                           OPTS_REPAIR_FULL),
    ("tz_roller_gates_size",      "C144", "Рул. ворота — размер",                      None),
    ("tz_roller_gates_count",     "D144", "Рул. ворота — кол-во",                      None),
    ("tz_roller_gates_type",      "E144", "Рул. ворота — тип",                         None),
    ("tz_roller_gates_comment",   "F144", "Рул. ворота — комментарий",                 None),
    ("tz_windows",                "B145", "Стеклопакеты",                              OPTS_REPAIR_FULL),
    ("tz_windows_size",           "C145", "Стеклопакеты — размер",                     None),
    ("tz_windows_count",          "D145", "Стеклопакеты — кол-во",                     None),
    ("tz_windows_type",           "E145", "Стеклопакеты — тип",                        None),
    ("tz_windows_comment",        "F145", "Стеклопакеты — комментарий",                None),
    ("tz_mgn",                    "B146", "Конструкции для МГН",                       OPTS_REPAIR_FULL),
    ("tz_mgn_size",               "C146", "МГН — размер",                              None),
    ("tz_mgn_count",              "D146", "МГН — кол-во",                              None),
    ("tz_mgn_type",               "E146", "МГН — тип",                                 None),
    ("tz_mgn_comment",            "F146", "МГН — комментарий",                         None),
    ("tz_fire_doors",             "B147", "Противопожарные двери",                     OPTS_REPAIR_FULL),
    ("tz_fire_doors_size",        "C147", "Прот. двери — размер",                      None),
    ("tz_fire_doors_count",       "D147", "Прот. двери — кол-во",                      None),
    ("tz_fire_doors_type",        "E147", "Прот. двери — тип",                         None),
    ("tz_fire_doors_comment",     "F147", "Прот. двери — комментарий",                 None),
    ("tz_grshe",                  "B148", "ГРЩ",                                       OPTS_REPAIR_FULL),
    ("tz_grshe_size",             "C148", "ГРЩ — размер",                              None),
    ("tz_grshe_count",            "D148", "ГРЩ — кол-во",                              None),
    ("tz_grshe_type",             "E148", "ГРЩ — тип",                                 None),
    ("tz_grshe_comment",          "F148", "ГРЩ — комментарий",                         None),
    ("tz_wash_robot",             "B149", "Поломоечная машина/робот",                  OPTS_WASH_ROBOT),

    # Section 8: Маркетинг
    ("mkt_facade_photos","B151","Получены фото фасада и входной группы",       OPTS_YES_NO),
    ("mkt_trc_photos",   "B152","Фото входной зоны ТРЦ (если в ТРЦ)",         OPTS_YES_NO),
    ("mkt_trc_navigation","B153","Нужна доп. навигация внутри ТРЦ",           OPTS_YES_NO),
    ("mkt_pattern",      "B154","Паттерн в ТЗ, нужно обновление?",            OPTS_YES_NO),
    ("mkt_ashel_mpc",    "B155","Лёгкая ашель и МНЦ над промо бинами",        OPTS_YES_NO),
    ("mkt_ashel_sof",    "B156","Сохранить ашель над СОФ",                    OPTS_YES_NO),
    ("mkt_posm",         "B157","Заказ POSM материалов для оформления",        OPTS_YES_NO),

    # Section 9: Иная важная информация (строки 159-177) — фиксированные поля
    ("who_demolition",        "A159","Кто проводит демонтаж, особенности по стройке",  None),
    ("work_restrictions",     "B160","Ограничения по работам (жилой дом и т.д.)",       None),
    ("lenta_online",          "B161","Лента Онлайн",                                    OPTS_YES_NO_OTHER),
    ("lenta_online_comment",  "C161","Лента Онлайн — комментарий",                      None),
    ("cctv",                  "B162","Система видеонаблюдения",                         OPTS_YES_NO_OTHER),
    ("cctv_comment",          "C162","Видеонаблюдение — комментарий",                   None),
    ("security_alarm",        "B163","Охранная сигнализация",                           OPTS_YES_NO_OTHER),
    ("security_alarm_comment","C163","Сигнализация — комментарий",                      None),
    ("antitheft_frames",      "B164","Антикражные рамки",                               OPTS_YES_NO_OTHER),
    ("antitheft_comment",     "C164","Антикражные рамки — комментарий",                 None),
    ("post1",                 "B165","Пост №1",                                         OPTS_YES_NO_OTHER),
    ("post1_comment",         "C165","Пост №1 — комментарий",                           None),
    ("new_ho",                "B166","Новое ХО",                                        OPTS_YES_NO_OTHER),
    ("new_ho_comment",        "C166","Новое ХО — комментарий",                          None),
    ("meat_workshop",         "B167","Мясной цех",                                      OPTS_YES_NO_OTHER),
    ("meat_workshop_comment", "C167","Мясной цех — комментарий",                        None),
    ("cryo_floors",           "B168","Полы в ХК",                                       OPTS_YES_NO_OTHER),
    ("cryo_floors_comment",   "C168","Полы в ХК — комментарий",                         None),
    ("mobile_signal",         "B169","Сотовая связь",                                   OPTS_YES_NO_OTHER),
    ("mobile_signal_comment", "C169","Сотовая связь — комментарий",                     None),
    ("walkie_talkie",         "B170","Рации",                                            OPTS_YES_NO_OTHER),
    ("walkie_talkie_comment", "C170","Рации — комментарий",                              None),
    ("fire_safety_lenta",     "B171","Пожарная безопасность за ООО Лента",              OPTS_YES_NO_OTHER),
    ("fire_safety_lenta_comment","C171","ПБ Лента — комментарий",                       None),
    ("fire_safety_ardd",      "B172","Пожарная безопасность за АРДД",                   OPTS_YES_NO_OTHER),
    ("fire_safety_ardd_comment","C172","ПБ АРДД — комментарий",                         None),
    ("receiving_room",        "B173","Комната приёмки товара",                          OPTS_YES_NO_OTHER),
    ("receiving_room_comment","C173","Комн. приёмки — комментарий",                     None),
    ("power_supply",          "B174","Электроснабжение",                                OPTS_YES_NO_OTHER),
    ("power_supply_comment",  "C174","Электроснабжение — комментарий",                  None),
    ("heat_supply",           "B175","Теплоснабжение",                                  OPTS_YES_NO_OTHER),
    ("heat_supply_comment",   "C175","Теплоснабжение — комментарий",                    None),
    ("water_supply",          "B176","Водоснабжение",                                   OPTS_YES_NO_OTHER),
    ("water_supply_comment",  "C176","Водоснабжение — комментарий",                     None),
    ("subrent_utilities",     "A177","Доп. вводы для субаренды (ХВС/ГВС/водоотведение/электроэнергия)", None),
]

# Free-text note sections with yellow headers in Excel
# key → (header_row, first_data_row, last_template_row, display_label)
FREE_TEXT_SECTIONS: dict[str, tuple[int, int, int, str]] = {
    "notes_main":    (178, 179, 183, "Иная важная информация"),
    "notes_fasad":   (184, 185, 191, "Фасад"),
    "notes_pb":      (192, 193, 195, "Пожарная безопасность"),
    "notes_elektro": (196, 197, 198, "Электроснабжение"),
    "notes_voda":    (199, 200, 203, "Водоснабжение"),
    "notes_teplo":   (204, 205, 210, "Теплоснабжение"),
}

# Quick lookup: key → (cell, label, options)
FIELD_MAP = {f[0]: (f[1], f[2], f[3]) for f in FIELDS}

# Dropdown options keyed by field name (for the HTML form)
DROPDOWN_OPTIONS: dict[str, list[str]] = {
    key: opts for key, cell, label, opts in FIELDS if opts
}


def get_template_path() -> Path:
    return TEMPLATE_PATH


def generate_excel(data: dict) -> bytes:
    """Open the adaptation template, write form values into 'Чек-лист', return bytes.

    All sheets, images and formatting from the original template are preserved.
    Fixed fields are written via FIELD_MAP.
    Free-text sections (multiline textarea) are split by newline and written into
    consecutive rows below each yellow header.
    """
    wb = openpyxl.load_workbook(str(TEMPLATE_PATH), keep_vba=False)

    ws = None
    for sheet in wb.worksheets:
        if sheet.title == SHEET_NAME:
            ws = sheet
            break
    if ws is None:
        ws = wb.worksheets[0]

    # Write fixed fields
    for key, value in data.items():
        entry = FIELD_MAP.get(key)
        if not entry or value is None or value == "":
            continue
        ws[entry[0]] = value

    # Write free-text sections (split by newline → individual rows in column B)
    for key, (header_row, start_row, end_row, _label) in FREE_TEXT_SECTIONS.items():
        text = data.get(key, "")
        if not text:
            continue
        lines = [ln for ln in text.replace("\r", "").split("\n") if ln.strip()]
        for i, line in enumerate(lines):
            ws.cell(row=start_row + i, column=1, value=line)  # A:F merged → write to A

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.read()
